# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitm" do
  version "1.0.14"

  on_macos do
    on_intel do
      sha256 "0e23e8cfdac4ef92d0996326b2b53ec69ad120e64691d30a883492714f064032"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9e579148666a94fda4209d792865272912679f54a6e079dfa27932fa2cbe566"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67a21eb52ff9053c6fc95dfb442d6e2d33ca9b66ed2d968a944ac1516d615cbc"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3f2ecf68d2c73832fc24bdf33b3cadbfbb009aab651ec272d27643f5cf5aa39"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitm"
  desc "Multi-repository git manager — run git operations across dozens of repositories in parallel"
  homepage "https://github.com/alexandreafj/gitm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitm"]
    end
  end

  # No zap stanza required

end
