# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitm" do
  version "1.0.26"

  on_macos do
    on_intel do
      sha256 "d751b3ec05b07667ad4e8ce4453bb4f2251f575f890512b000f50c89c86a9f51"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee125a7884eff127a258ed7726fe35babfd8ff4019cf417b7ad5a0b53c8c51f9"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "712ed5e267f91f9b7bd43119732aed45cc206616406319963bcc8e277b38947d"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab0c055b97644f7eba30b224f65cc2261f4757fc8940ea0093c718bcea516d11"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitm"
  desc "Multi-repository git manager — run git operations across dozens of repositories in parallel"
  homepage "https://github.com/alexandreafj/gitm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitm"]
    end
  end

  # No zap stanza required

end
