# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitm" do
  version "1.0.35"

  on_macos do
    on_arm do
      sha256 "a14749d7add589f29292b67f09c1dbef0ce7823762370feb830b440b7a55e06a"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e50886eff3fda5dc54d1a55b99742c2efc787fe805a468bc7f2690af88021820"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0837555e5d39d293938a5eee01d4fea124e288c8ab64138080da72ce58b62b6a"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f260c7db8b0dae06be108f93a117601550e29fbe5c47b0a15fa23ef5c2b15fb"
      url "https://github.com/alexandreafj/gitm/releases/download/v#{version}/gitm_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitm"
  desc "Multi-repository git manager — run git operations across dozens of repositories in parallel"
  homepage "https://github.com/alexandreafj/gitm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitm"]
    end
  end

  # No zap stanza required
end
